name: app_webdeploy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_remote_config: ^4.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.1.0
  flutter_localization: ^0.1.13
  flutter_pdfview: ^1.3.1
  intl: ^0.18.0
  pdf: ^3.10.4
  universal_html: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/stores.jpg
